apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
  namespace: zad5
spec:
  containers:
  - image: nginx
    name: worker
    resources:
      limits:
       memory:  200Mi
       cpu:  200m
      requests:
       memory:  100Mi
       cpu:  100m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
